### ISSUE TITLE
Relative or cwd paths

### ISSUE THREAD

**Issue by YodaEmbedding** [hrsh7th/cmp-path#10]
Feature request: complete paths from the current working directory or relative paths (`./file`, `../file`, ...).

These completions should only occur if the cursor is at the start of a string character (typically `"` or `'`) or if in a shell script (`.sh`, `.zsh`, `#!/bin/bash`).

**Comment by sudoforge** [comment]
`./` and `../` currently work.

_relative paths_, without a leading `./`, do not.
