### ISSUE TITLE
Not Triggering within quotes

### ISSUE THREAD

**Issue by redxtech** [hrsh7th/cmp-path#18]
Hey! I recently started using this, and for some reason I've been unable to trigger path completion from within quotes (both single and double).

Is this intended behavior? If so, is there a way to enable path completion from within quotes?

**Comment by hrsh7th** [comment]
I've fixed it.

**Comment by redxtech** [comment]
Amazing, thank you!

**Comment by TheBlob42** [comment]
Just as a follow up I realized that I can not trigger path completion within quotes (single and double) if I start with `~` for the home directory (other absolute and relative paths work fine)

Should I open a separate issue for this? :thinking:

**Comment by hrsh7th** [comment]
What do you mean?
I can trigger completion with `"~/|"` (`|` is cursor)

**Comment by TheBlob42** [comment]
Ok thats weird :sweat_smile: 
I have just updated to nvim 0.6 and updated all my plugins, but it does not work for me (all other path completion does)

Let me create a minimal config, not that this is another plugin interfering somehow

**Comment by TheBlob42** [comment]
I tried with the following minimal config:

```lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
local is_packer_installed = vim.fn.isdirectory(install_path) == 1
if not is_packer_installed then
    vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end

require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use 'hrsh7th/cmp-path'
    use 'hrsh7th/nvim-cmp'
end)

require('cmp').setup {
    sources = {
        { name = 'path' }
    }
}
```
![example](https://user-images.githubusercontent.com/6849129/144599227-c20cd12a-d4f9-4c23-bbab-25d58ebcc95d.gif)

Could that have something to do with the new `0.6` version (maybe a VIM patch or some small change)?

**Comment by hrsh7th** [comment]
Ah. Sorry. My local version was modified...

**Comment by nyngwang** [comment]
> Just as a follow up I realized that I can not trigger path completion within quotes (single and double) if I start with ~ for the home directory (other absolute and relative paths work fine)

I have the same issue :/
