### ISSUE TITLE
wildcard completion leads to wrong path with `Insert`+`Replace` behaviour

### ISSUE THREAD

**Issue by msva** [hrsh7th/cmp-path#19]
Hi there!

I've find following issue: if I type, say, `:e files/*peg<Tab>` and select appropriate file from the list, then I'll get `:e files/*files/vtk-9.0.3-pegtl-3.patch` in the command line.

Looks like there is a typo somewhere, that makes it to not replace old text in such cases...

**Comment by msva** [comment]
> Label: can't understand

ok, here is asciinema record: https://asciinema.org/a/QFhV8Qeh0eRSsixcutzGu9qtE

Also, I've found another strange behaviour (not sure, if it is one more variant of this issue, or a separate one):
https://asciinema.org/a/cGEwqs1k77Cf0ZU2i1ZNGowqe

**Comment by hrsh7th** [comment]
duplicate https://github.com/hrsh7th/cmp-cmdline/issues/17

**Comment by msva** [comment]
Yeah, thanks, I just noticed that the source of that was `cmdline` plugin. Sorry :)

**Comment by msva** [comment]
Although, https://asciinema.org/a/cGEwqs1k77Cf0ZU2i1ZNGowqe (thing I mentioned in last comment) is not about wildcards (but may still be related there)
