### ISSUE TITLE
paths relative to the working directory

### ISSUE THREAD

**Issue by Frydac** [hrsh7th/cmp-path#21]
Hi,

I think the relative paths work relative to the parent directory of the file I'm currently editing.
Generally I want paths relative to the project the file belongs to, which I usually setup as my vim working directory.

For me it would be fine if both the parent dir and the cwd are used initially until only a unique match exists.
Or if it is an option to choose either one or the other would also be fine for me.
Or something else you come up with.. (lsp root dir might also be a good candidate)

For now I've made a small edit locally in the plugin source so I get the relative path to my cwd, so no pressure :)

Thank you so much for all this stuff, just starting to migrate nvim with lua based plugins and built in lsp since I have holidays, I'm enjoying myself very much, and I'm amazed by cmp, great work!

**Comment by ten3roberts** [comment]
I second this. I always use project.nvim to set my cwd to the git repo. Since the program which will read the filepaths are going to look for them in the project dir, not that specific source file dir, it makes sense to have an option for paths relative to cwd.

**Comment by ten3roberts** [comment]
I'd gladly use your edit if you upload it to your github as a fork.

If your edit works well, you could open a PR and maybe get it merged without @hrsh7th doing all the work.

**Comment by hrsh7th** [comment]
```
{ name = 'path', option = {
  get_cwd = function()
  end
} }
```

I can merge the above API.

**Comment by ten3roberts** [comment]
How is this issue getting along.

I may be wrong, but it does not seem as if above change has been made.

**Comment by hrsh7th** [comment]
I thoughts someone create the PR the above design.

**Comment by ten3roberts** [comment]
I thought something like that.

As it is now, it will always lookup the current buffer name and use fs_stat now.

If I've understood it correctly, the above API allow you to exchange the `source._dirname` function with your own in complete, fed into `'candidates`.

If that is the case, I will gladly implement it and open a PR.

Thanks so much for this plugin.

**Comment by maxnoe** [comment]
Hi,

How should I define `get_cwd` If I want relative paths to be resolved from the working directory where I start vim, not the path of the file I am currently editing?

**Comment by acro5piano** [comment]
@maxnoe 

This should work.

```lua
  get_cwd = function(params)
    return vim.fn.getcwd()
  end,
```

I've also created a small fork to have both cwd and the path of the buffer file.

https://github.com/acro5piano/cmp-path-chdir
