### ISSUE TITLE
Latest commit (56a0fe5c4) breaks path completion after second `/`

### ISSUE THREAD

**Issue by walkert** [hrsh7th/cmp-path#23]
Hi - first, great plugin!

I noticed today that completion would start to break after the second `/`. The first `/` opens completion for paths. If I select the first path and then type the next `/` it shows me only snippets that match `/` like `if/else`. Reverting to `d83839ae` resolves this issue and the source works as before.

Thanks

**Comment by kflak** [comment]
Can confirm both the bug and the suggested fix.

**Comment by JosefLitos** [comment]
Please excuse my ignorance, but I cannot find a way to revert to the commit, since I just installed the plugin so the first revision I have locally seems to be the latest commit.

**Comment by kflak** [comment]
Depends on how you install your plugins. I use `packer`, and this works:
```
        use {
            'hrsh7th/cmp-path',
            commit = 'd83839ae'
        }
```

**Comment by marcushwz** [comment]
I have the same problem, but after reverting to that said commit, no completion is triggered for path at all

**Comment by hrsh7th** [comment]
@marcushwz is fixed this. Thank you.
