### ISSUE TITLE
Prevent preview generation of device files but still list them.

### ISSUE THREAD

**Issue by oddlama** [hrsh7th/cmp-path#25]
One of the recent commits tried to remove the ability to complete device files.
Unfortunately, when completing a link to a device file, or any path not starting with `/dev`
directly, still has the potential to kill vim. Consider this:

```bash
ln -s /dev/stdin dead
```

Then try completing `./dea<TAB>` and nvim is dead as it tries to read from the pty `/dev/stdin`.
Instead of preventing preview generation based on the path, it would be much better to stat
the file beforehand and return an empty preview in case the file is not a regular file or directory (or a symlink to one of these).
Stat can follow symbolic links, and they should be to prevent the above scenario.

On a related note: I seem to be unable to complete anything with more than two path component. No completion for `/dev`
is ever shown, but I suppose this is not directly related to this bug.

**Comment by dmitmel** [comment]
Fair. Files with `vim.loop.fs_stat(path).type == 'char'` can be ignored.
