### ISSUE TITLE
Complete paths relative to current file

### ISSUE THREAD

**Issue by Hubro** [hrsh7th/cmp-path#39]
It's often useful to be able to complete paths relative to the *current file*, not just relative to the working directory. For example, given this working directory:

```
.
├── lib
└── public
    ├── css
    │   └── screen.css
    ├── img
    │   ├── image-1.png
    │   ├── image-2.png
    │   └── image-3.png
    ├── index.html
    └── js
        ├── carousel.js
        └── login.js
```

It would be very useful to be able to complete paths like `img/image-2.png` when working on the `index.html` file. This works as expected in vscode.

I think that when `cmp-path` is suggesting relative paths, it should include paths relative to the current file. Or, at the very least, it should be an option to enable this.

**Comment by hrsh7th** [comment]
See this document.
https://github.com/hrsh7th/cmp-path#get_cwd-type-function
