### ISSUE TITLE
Overriding import statementes suggestions from a language server (`tsserver`)?

### ISSUE THREAD

**Issue by Pocco81** [hrsh7th/cmp-path#4]
Hey! I was having some issues with `cmp-path` where it "overrides" import statements when trying to import from a directory.

Example:

Here I'm trying to import a file inside of `modules/`, and for that I type `./` in order to get the suggestions:

![image](https://user-images.githubusercontent.com/58336662/132151359-1df1f947-e39d-489d-bbe5-4e7827de8bd0.png)

With `cmp-path` I expect to get suggestions from the lsp (tsserver) on top of the ones from `cmp-path`, because that's how I have it configured, but instead the suggestions from the lsp don't appear, and the ones from `cmp-path` do.

Is this bug or is it intended for `cmp-path` to "override" lsp suggestions? Or perhaps there is an issue with [my setup](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/main/.config/nvim/lua/nvdope/initialization/tools/cmp.lua#L107)?

**Comment by hrsh7th** [comment]
Thank you. I've fixed it.

**Comment by Pocco81** [comment]
Thank you :)
