### ISSUE TITLE
Hidden files/directories are not shown

### ISSUE THREAD

**Issue by py2048** [hrsh7th/cmp-path#5]
When I type `.` in PATH, it is expected to see all the files/dirs (like nvim-compe). However they are not appeared:
![Screen Shot 2021-09-11 at 21 25 56](https://user-images.githubusercontent.com/66913697/132951318-294189c7-78fa-4d75-bd09-eeb4e59a4217.png)

I am not really sure but when I change the line:
https://github.com/hrsh7th/cmp-path/blob/3a29c5131a4c6b319849362a2eecba9d8b1a4aac/lua/cmp_path/init.lua#L93
to: 
```lua
  local include_hidden = string.sub(params.context.cursor_before_line, offset , offset) == '.'
```
It fixed the issue and I can see all the hidden files
![Screen Shot 2021-09-11 at 21 27 32](https://user-images.githubusercontent.com/66913697/132951413-43258ce8-3af1-40dd-9ec5-1a68f37958d2.png)

**Comment by hrsh7th** [comment]
Please send PR. I think your suggestion is correct.

**Comment by py2048** [comment]
Ok here it is https://github.com/hrsh7th/cmp-path/pull/6

**Comment by zigotica** [comment]
Hi, is it possible I am seeing a regression? Using latest cmp-path in neovim 0.7, and I can only get visible files and folders in the completion menu. 

Thank you

**Comment by ExtinctAxolotl** [comment]
Same problem for me. Using latest cmp-path and cmp on neovim 0.6, and only getting this:
![image](https://user-images.githubusercontent.com/62254492/146541009-eaf94049-cb84-4891-aa49-e5e942535c09.png)

**Comment by zigotica** [comment]
OK, updated my plugs and it is working now

**Comment by astier** [comment]
I am still having this issue. I can reproduce it with the following init.vim:

```vim
call plug#begin()
  Plug 'hrsh7th/cmp-path'
  Plug 'hrsh7th/nvim-cmp'
call plug#end()

lua << EOF
local cmp = require 'cmp'
cmp.setup {
  sources = cmp.config.sources({
    { name = 'path' },
  }),
}
EOF
```

**Comment by astier** [comment]
Nevermind. Different issue.
