### ISSUE TITLE
Completion in the middle of a path does not work

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/cmp-path#7]
Hi

When triggering completion in the middle of a path, for example placing the cursor after the following: "/tmp/fil", will not suggest "/tmp/file". This is probably due to the trigger characters expecting a '/' or a '.' . 

Any way to examine the preceding line to decide if completions should be generated? Maybe support a functional override for trigger characters?

**Comment by hrsh7th** [comment]
I've fixed now. It is a logic problem.

**Comment by tzachar** [comment]
10x.
